company/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AgentViewSet, CompanyViewSet, EmployeeViewSet, AgreementViewSet, CategoryViewSet, CategoryRaymentsViewSet, EmployeeToAgreementViewSet

router = DefaultRouter()
router.register(r'agents', AgentViewSet)  # URL для агентов
router.register(r'companies', CompanyViewSet)  # URL для компаний
router.register(r'employees', EmployeeViewSet)
router.register(r'agreements', AgreementViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'category_payments', CategoryRaymentsViewSet)
router.register(r'employee_to_agreement', EmployeeToAgreementViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.index, name='index'),
    path('agents/', views.agents, name='agents'),
    path('agents/add_agent/', views.agent_create, name='add_agent'),
    path('agents/update_agent/', views.update_agent, name='update_agent'),
    path('agents/delete_agent/', views.delete_agent, name='delete_agent'),
    path('companies/', views.companies, name='companies'),
    path('companies/add_company/', views.create_company, name='add_company'),
    path('companies/update_company/', views.update_company, name='update_company'),
    path('companies/delete_company/', views.delete_company, name='delete_company'),
    path('employees/', views.employees, name='employees'),
    path('agreements/', views.agreements, name='agreements'),
    path('employees/add_employee/', views.add_employee, name='add_employee'),
    path('employees/update_employee/', views.update_employee, name='update_employee'),
    path('employees/delete_employee/', views.delete_employee, name='delete_employee'),
    path('employees/add_category/', views.add_category, name='add_category'),
    path('agreements/add-agreement/', views.add_agreement, name='add_agreement'),
    path('agreement/add_payment/', views.add_category_payment, name='add_category_payment'),
    path('agreements/employee/', views.add_employee_to_agreement, name='add_employee_to_agreement'),
    path('search1', views.search1, name='search1'),
    path('search2', views.search2, name='search2'),
    path('search3', views.search3, name='search3'),
]


'''
path('agreements/add-agreement/', views.add_agreement, name='add_agreement'),
path('agreements/add-payments/<int:agreement_id>/', views.add_payments, name='add_payments'),




'''

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
]

company/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Agent(models.Model):
    agent_id = models.AutoField(primary_key=True)
    agent_name = models.CharField(max_length=255)
    agent_passport_id = models.CharField(max_length=50)
    agent_passport_number = models.CharField(max_length=50)
    agent_passport_date = models.DateField()

    class Meta:
        managed = False
        db_table = 'agent'


class Agreement(models.Model):
    agreement_id = models.AutoField(primary_key=True)
    agreement_start_date = models.DateField()
    agreement_end_date = models.DateField()
    agreement_total_payments = models.FloatField()
    agent = models.ForeignKey(Agent, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'agreement'



class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    employee = models.OneToOneField('Employee', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'category'


class CategoryPayment(models.Model):
    category_payment_id = models.AutoField(primary_key=True)
    payment_amount = models.FloatField()
    category = models.ForeignKey(Category, models.DO_NOTHING, blank=True, null=True)
    agreement = models.ForeignKey(Agreement, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'category_payment'


class Company(models.Model):
    company_id = models.AutoField(primary_key=True)
    company_number = models.IntegerField()
    company_full_name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=100)
    company_address = models.CharField(max_length=255)
    company_bank_number = models.CharField(max_length=50)
    company_specialization = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'company'


class Employee(models.Model):
    employee_id = models.AutoField(primary_key=True)
    employee_name = models.CharField(max_length=255)
    employee_age = models.IntegerField()
    company = models.ForeignKey(Company, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'employee'


class EmployeeToAgreement(models.Model):
    employee_to_agreement_id = models.AutoField(primary_key=True)
    employee = models.ForeignKey(Employee, models.DO_NOTHING, blank=True, null=True)
    agreement = models.ForeignKey(Agreement, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'employee_to_agreement'

company/views.py
from rest_framework import viewsets
from .serializers import AgentSerializer, CompanySerializer, EmployeeSerializer, AgreementS, EmployeeToAgreementS, CategoryPaymentS, CategoryS
from django.shortcuts import render, redirect
from .forms import AgentForm, UpdateAgentForm, DeleteAgentForm, AddCompany, UpdateCompany, DeleteCompany, AddEmployeeForm, UpdateEmployeeForm, DeleteEmployeeForm, AddCategoryForm, AddAgreementForm, AddCategoryPayment, AddEmployeeToAgreement, Search1, Search3
from django.db import connection, IntegrityError, DatabaseError
from django.contrib import messages
from .models import Company, Agent, Employee, Agreement, CategoryPayment, Category, EmployeeToAgreement


class AgentViewSet(viewsets.ModelViewSet):
    queryset = Agent.objects.all()
    serializer_class = AgentSerializer

class CompanyViewSet(viewsets.ModelViewSet):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer

class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

class AgreementViewSet(viewsets.ModelViewSet):
    queryset = Agreement.objects.all()
    serializer_class = AgreementS

class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategoryS

class EmployeeToAgreementViewSet(viewsets.ModelViewSet):
    queryset = EmployeeToAgreement.objects.all()
    serializer_class = EmployeeToAgreementS

class CategoryRaymentsViewSet(viewsets.ModelViewSet):
    queryset = CategoryPayment.objects.all()
    serializer_class = CategoryPaymentS

def index(request):
    # Получение списка всех компаний из базы данных
    companies = Company.objects.all()
    return render(request, 'company/index.html', {'companies': companies})


def agents(request):
    agents = Agent.objects.all()
    return render(request, 'company/agents.html', {'agents': agents})

def employees(request):
    employees = Employee.objects.select_related('company') \
        .prefetch_related('employeetoagreement_set__agreement').all()
    return render(request, 'company/employees.html', {'employees': employees})

def companies(request):
    companies = Company.objects.all()
    return render(request, 'company/companies.html', {'companies': companies})

def agreements(request):
    agreements = Agreement.objects.select_related('agent').all()
    category_payments = CategoryPayment.objects.all()
    return render(request, 'company/agreements.html', {'agreements': agreements, 'payments': category_payments})

def add_agent_function(agent_name, passport_id, passport_number, passport_date):
    with connection.cursor() as cursor:
        try:
            cursor.execute("""
                CALL add_agent(%s, %s, %s, %s);
            """, [agent_name, passport_id, passport_number, passport_date])
        except Exception as e:
            # Если возникает ошибка, возвращаем ее текст для отображения
            raise IntegrityError(str(e))

def agent_create(request):
    if request.method == 'POST':
        form = AgentForm(request.POST)
        if form.is_valid():
            agent_name = form.cleaned_data['agent_name']
            passport_id = form.cleaned_data['agent_passport_id']
            passport_number = form.cleaned_data['agent_passport_number']
            passport_date = form.cleaned_data['agent_passport_date']
            
            try:
                # Попытка добавить агента
                add_agent_function(agent_name, passport_id, passport_number, passport_date)
                # Перенаправляем на страницу после успешного добавления
                return redirect('agents')  # Замените на нужную страницу
            except IntegrityError as e:
                # Если возникает ошибка, добавляем сообщение
                messages.error(request, str(e))  # Отправляем сообщение об ошибке в шаблон

    else:
        form = AgentForm()

    return render(request, 'company/agent_create.html', {'form': form})

def update_agent(request):
    error_message = None  # Переменная для хранения ошибки

    if request.method == 'POST':
        form = UpdateAgentForm(request.POST)
        if form.is_valid():
            # Получаем данные из формы
            agent_id = form.cleaned_data['agent_id'].agent_id
            agent_name = form.cleaned_data['agent_name']
            agent_passport_id = form.cleaned_data['agent_passport_id']
            agent_passport_number = form.cleaned_data['agent_passport_number']
            agent_passport_date = form.cleaned_data['agent_passport_date']

            # Вызов функции update_agent через SQL-запрос
            try:
                with connection.cursor() as cursor:
                    cursor.execute("""
                        CALL update_agent(%s, %s, %s, %s, %s);
                    """, [agent_id, agent_name, agent_passport_id, agent_passport_number, agent_passport_date])

                # Перенаправляем пользователя после успешного обновления
                return redirect('agents')  # Замените 'success_url' на нужный URL после обновления

            except DatabaseError as e:
                # Если PostgreSQL выбросил исключение, обрабатываем его
                error_message = str(e)  # Получаем текст ошибки

    else:
        form = UpdateAgentForm()

    return render(request, 'company/update_agent.html', {'form': form, 'error_message': error_message})

def delete_agent_function(agent_id):
    with connection.cursor() as cursor:
        try:
            cursor.execute("""
                CALL delete_agent(%s);
            """, [agent_id])
        except Exception as e:
            # Возвращаем ошибку, если агент не найден
            raise IntegrityError(str(e))

def delete_agent(request):
    if request.method == 'POST':
        form = DeleteAgentForm(request.POST)
        if form.is_valid():
            agent_id = form.cleaned_data['agent_id'].agent_id
            
            try:
                # Попытка удалить агента
                delete_agent_function(agent_id)
                # Перенаправляем на страницу после успешного удаления
                return redirect('agents')  # Замените на нужную страницу
            except IntegrityError as e:
                # Если возникает ошибка, добавляем сообщение
                messages.error(request, str(e))  # Отправляем сообщение об ошибке в шаблон

    else:
        form = DeleteAgentForm()

    return render(request, 'company/delete_agent.html', {'form': form})


def create_company(request):
    if request.method == "POST":
        form = AddCompany(request.POST)
        if form.is_valid():
            company_number = form.cleaned_data['company_number']
            company_full_name = form.cleaned_data['company_full_name']
            company_name =form.cleaned_data['company_name']
            company_address = form.cleaned_data['company_address']
            company_bank_number = form.cleaned_data['company_bank_number']
            company_specialization = form.cleaned_data['company_specialization']

            with connection.cursor() as cursor:
                try:
                    cursor.execute("""
                        CALL add_company(%s, %s, %s, %s, %s, %s)""", [ company_number, company_full_name, company_name, company_address, company_bank_number, company_specialization])

                    return redirect('companies')
                
                except Exception as e:
                    # Возвращаем ошибку, если агент не найден
                    messages.error(request, str(e))
    else:
        form = AddCompany()

    return render(request, 'company/add_company.html', {'form': form})


def update_company(request):
    if request.method == "POST":
        form = UpdateCompany(request.POST)
        if form.is_valid():
            company_id = form.cleaned_data['company_id']
            company_number = form.cleaned_data['company_number']
            company_full_name = form.cleaned_data['company_full_name']
            company_name =form.cleaned_data['company_name']
            company_address = form.cleaned_data['company_address']
            company_bank_number = form.cleaned_data['company_bank_number']
            company_specialization = form.cleaned_data['company_specialization']

            with connection.cursor() as cursor:
                try:
                    cursor.execute("""
                        CALL update_company(%s, %s, %s, %s, %s, %s, %s)""", [company_id, company_number, company_full_name, company_name, company_address, company_bank_number, company_specialization])

                    return redirect('companies')
                
                except Exception as e:
                    # Возвращаем ошибку, если агент не найден
                    messages.error(request, str(e))
    else:
        form = UpdateCompany()

    return render(request, 'company/update_company.html', {'form': form})


def delete_company(request):
    if request.method == "POST":
        form = DeleteCompany(request.POST)
        if form.is_valid():
            company_id = form.cleaned_data['company_id'].company_id

            with connection.cursor() as cursor:
                try:
                    cursor.execute("""
                        CALL delete_company(%s)""", [company_id])

                    return redirect('companies')
                
                except Exception as e:
                    # Возвращаем ошибку, если агент не найден
                    messages.error(request, str(e))
    else:
        form = DeleteCompany()

    return render(request, 'company/delete_company.html', {'form': form})


def add_employee(request):
    if request.method == "POST":
        form = AddEmployeeForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['employee_name']
            age = form.cleaned_data['employee_age']
            company = form.cleaned_data['company']
            if company == None:
                messages.error(request, "No companies")

company/templates/company/add_agreement.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить договор</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Добавить договор</h1>

        {% if messages %}
            {% for message in messages %}
            <div style="color: red;">
                <strong>Error:</strong> {{ message }}
            </div>
            {% endfor %}
        {% endif %}

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать договор</button>
        </form>
    
        
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

company/templates/company/add_category_payment.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить выплаты к категории</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Добавить выплаты к категории</h1>

        <!-- Вывод сообщений об ошибках -->
        {% if messages %}
            {% for message in messages %}
            <div style="color: red;">
                <strong>Error:</strong> {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        
        <!-- Форма для добавления агента -->
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

company/templates/company/add_company.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить компанию</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Добавить компанию</h1>

        <!-- Вывод сообщений об ошибках -->
        {% if messages %}
            {% for message in messages %}
            <div style="color: red;">
                <strong>Error:</strong> {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        
        <!-- Форма для добавления агента -->
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить компанию</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

company/templates/company/add_employee.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить сотрудника</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Добавить компанию</h1>

        <!-- Вывод сообщений об ошибках -->
        {% if messages %}
            {% for message in messages %}
            <div style="color: red;">
                <strong>Error:</strong> {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        
        <!-- Форма для добавления агента -->
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить сотрудника</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

company/templates/company/agent_create.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить агента</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Добавить агента</h1>

        <!-- Вывод сообщений об ошибках -->
        {% if messages %}
            {% for message in messages %}
            <div style="color: red;">
                <strong>Error:</strong> {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        
        <!-- Форма для добавления агента -->
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить агента</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

company/templates/company/agreements.html
<!-- myapp/templates/home.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Договора</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   
</head>
<body>
    <header class="d-flex justify-content-center py-3">
        <ul class="nav nav-pills justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Главная</a></li>
          <li class="nav-item"><a href="{% url 'agents' %}" class="nav-link">Агенты</a></li>
          <li class="nav-item"><a href="{% url 'employees' %}" class="nav-link">Сотрудники</a></li>
          <li class="nav-item"><a href="{% url 'companies' %}" class="nav-link">Компании</a></li>
          <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Договора</a></li>
        </ul>
      </header>
      <div class="container mt-5">
        <h1 class="mb-4">Список договоров</h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Номер договора</th>
                    <th>Дата начала соглашения</th>
                    <th>Дата окончания соглашения</th>
                    <th>Общая сумма страховых выплат</th>
                    <th>Агент, заключивший договор</th>
                </tr>
            </thead>
            <tbody>
                {% for agreement in agreements %}
                    <tr>
                        <td>{{ agreement.agreement_id }}</td>
                        <td>{{ agreement.agreement_start_date }}</td>
                        <td>{{ agreement.agreement_end_date }}</td>
                        <td>{{ agreement.agreement_total_payments }}</td>
                        <td>{{ agreement.agent.agent_name }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">Нет договоров</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container mt-5">
        <h1 class="mb-4">Список выплат по договорам </h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Номер договора</th>
                    <th>Категория выплат</th>
                    <th>Сотрудник</th>
                    <th>Сумма выплат</th>
                </tr>
            </thead>
            <tbody>
                {% for payment in payments %}
                    <tr>
                        <td>{{ payment.agreement.agreement_id }}</td>
                        <td>{{ payment.category.name}}</td>
                        <td>{{ payment.category.employee.employee_name }}</td>
                        <td>{{ payment.payment_amount }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">Нет договоров</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-center gap-1 mb-5">
        <div class="pricing-header p-3 pb-md-4 text-center">
            <!-- Ссылка для открытия модального окна -->
        <a href="{% url 'add_agreement' %}"  class="btn btn-lg btn-primary" style="width: 200px;">
            Добавить договор
        </a>
    </div>
    
    <div class="pricing-header p-3 pb-md-4 text-center">
        <!-- Ссылка для открытия модального окна -->
    <a href="{% url 'add_category_payment' %}"  class="btn btn-lg btn-primary" style="width: 200px;">
        Добавить выплаты
    </a>
</div>

    <div class="pricing-header p-3 pb-md-4 text-center">
        <!-- Ссылка для открытия модального окна -->
        <a href="{% url 'add_employee_to_agreement' %}"  class="btn btn-lg btn-primary" style="width: 200px;">
            Добавить сотрудника в договор
        </a>
    </div>
    </div>
</body>
</html>

company/templates/company/delete_agent.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Удалить агента</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Удалить агента</h1>

        {% if messages %}
            {% for message in messages %}
            <div style="color: red;">
                <strong>Error:</strong> {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        
        <!-- Форма для удаления агента -->
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Удалить агента</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

company/templates/company/delete_company.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Удаление компанию</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Удаление компанию</h1>

        <!-- Вывод сообщений об ошибках -->
        {% if messages %}
            {% for message in messages %}
            <div style="color: red;">
                <strong>Error:</strong> {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        
        <!-- Форма для добавления агента -->
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Удалить компанию</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

company/templates/company/employees.html
<!-- myapp/templates/home.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Сотрудники</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   
</head>
<body>
    <header class="d-flex justify-content-center py-3">
        <ul class="nav nav-pills justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Главная</a></li>
          <li class="nav-item"><a href="{% url 'agents' %}" class="nav-link">Агенты</a></li>
          <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Сотрудники</a></li>
          <li class="nav-item"><a href="{% url 'companies' %}" class="nav-link">Компании</a></li>
          <li class="nav-item"><a href="{% url 'agreements' %}" class="nav-link">Договора</a></li>
        </ul>
      </header>
      <div class="container mt-5">
        <h1 class="mb-4">Список сотрудников</h1>
        <!-- Таблица для отображения агентов -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ФИО</th>
                    <th>Возраст</th>
                    <th>Категория выплат</th>
                    <th>Название компании</th>
                    <th>Договор</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                    <tr>
                        <td>{{ employee.employee_name }}</td>
                        <td>{{ employee.employee_age }}</td>
                        <td>
                                    {% if employee.category %}
                                {{ employee.category.name }}
                            {% else %}
                                Нет категории
                            {% endif %}
                        </td>
                        <td>{{ employee.company.company_name }}</td>
                        <td>
                            <ul>
                                {% for ea in employee.employeetoagreement_set.all %}
                                    <li>
                                        Договор ID: {{ ea.agreement.agreement_id }}
                                    </li>
                                {% empty %}
                                    Нет договоров
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>

                {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">Нет сотрудников</td>
                    </tr>
                
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-center gap-1 mb-5">
        <div class="pricing-header p-3 pb-md-4 text-center">
            <!-- Ссылка для открытия модального окна -->
        <a href="{% url 'add_employee' %}"  class="btn btn-lg btn-primary" style="width: 200px;">
            Добавить сотрудника
        </a>
    </div>
    <div class="pricing-header p-3 pb-md-4 text-center">
        <!-- Ссылка для открытия модального окна -->
    <a href="{% url 'update_employee' %}"  class="btn btn-lg btn-primary" style="width: 200px;">
        Изменить сотрудника
    </a>
</div>
<div class="pricing-header p-3 pb-md-4 text-center">
    <!-- Ссылка для открытия модального окна -->
<a href="{% url 'delete_employee' %}"  class="btn btn-lg btn-primary" style="width: 200px;">
    Удалить сотрудника
</a>
</div>
    
    </div>

    <div class="d-flex justify-content-center gap-1 mb-5">
    <div class="pricing-header p-3 pb-md-4 text-center">
        <!-- Ссылка для открытия модального окна -->
    <a href="{% url 'add_category' %}"  class="btn btn-lg btn-primary" style="width: 200px;">
        Добавить категорию
    </a>
    </div>

    
    </div>
</body>
</html>